$accent = rgb(6B8E97)
$accentAlpha = 6B8E97
$text = rgb(d2cabe)
$font = JetBrains Mono Nerd Font
general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/light_roronoa/Downloads/wallpapers/image.png
    blur_passes = 2
    color = rgb(0c0b1f)
}

label {
    monitor =
    text = cmd[update:1] echo "$(date +"%I:%M:%S %p")"
    color = $text
    font_size = 90
    font_family = $font
    position = -15, -130
    halign = center
    valign = top
}

label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $text
    font_size = 25
    font_family = $font
    position = -15, -280
    halign = center
    valign = top
}

image {
    monitor = 
    path = ~/.face
    size = 100
    border_color = $accent
    position = 0, 75
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = rgb(0c0b1f)
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##cdd6f4"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = rgb(965272)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(BD9176)
    position = 0, -35
    halign = center
    valign = center
}
