# Style and colors generated for the karla theme.

[global]
origin = top-right
offset = (20, 60)

transparency = 8
corner_radius = 0

frame_width = 2
frame_color = "#353c52"

font = JetBrainsMono NF Medium 9
icon_theme = "Sweet-Rainbow, Adwaita""

format = "<span size='xx-large' font_desc='Cantarell 9' weight='bold' foreground='#5884d4'>%s</span>\n%b"

[urgency_low]
timeout = 3
background = "#0E1113"
foreground = "#61b33e"

[urgency_normal]
timeout = 5
background = "#0E1113"
foreground = "#afb1db"

[urgency_critical]
timeout = 0
background = "#0E1113"
foreground = "#e7034a"
