pulse.cmd = [
    { cmd = "load-module" args = "module-ladspa-source source_name=rnnoise_source master=bluez_input.65:70:1D:EB:EC:AE plugin=librnnoise_ladspa label=noise_suppressor_mono control=50,200,100,0,0" }
]
