#!/bin/bash
wallpaper=$(find ~/Downloads/wallpapers -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" \) | shuf -n 1)
if [ -n "$wallpaper" ]; then
    wal -i "$wallpaper" -n -q

    # Update Hyprland borders
    . ~/.cache/wal/colors.sh
    hyprctl keyword general:col.active_border "0xff${color1:1} 0xff${color2:1} 45deg"
    hyprctl keyword general:col.inactive_border "0xff${color0:1}"

    swww img "$wallpaper" --transition-type random --transition-duration 2
    pkill -SIGUSR2 waybar
fi
